### ISSUE TITLE
Dead video embed

### ISSUE THREAD

**Issue by ostyn** [dohnutt/eric#1]
Video mentioned here, https://ericmoss.ca/jesus/, is dead. Recommendation: Resurrect Jesus.

Also, slick site #notastalker

**Comment by ostyn** [comment]
Bonus round! Forgot to mention that the video is loading from the http, not https YouTube. In Chrome it kind of masks the original issue by...[ just hiding the embed.](https://support.google.com/chrome/answer/1342714?p=unauthenticated&visit_id=0-636302074991660584-4020890181&rd=1). 

I don't know when they started doing this, but I need to fix it on my site too.

**Comment by dohnutt** [comment]
Haha thanks for the heads up. This code is actually for my new site, which is not yet live. I was planning on using this video https://m.youtube.com/watch?v=jyYFxp7apl4 but I'll check out Ressurect Jesus.

**Comment by dohnutt** [comment]
Oh boy @ostyn... just realized that "resurrect jesus" was a joke not a reference to a video hahah...

**Comment by ostyn** [comment]
Haha, yep... Nice! Sounds good.
